//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWLOTPH.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialEmpiricalCoefficients
    {
        public double consistencyIndexMaterial { get; set; }
        public int ID { get; set; }
        public double indexOfMaterialFlow { get; set; }
        public double temperatureReduction { get; set; }
        public double theHeatTransferCoefficient { get; set; }
        public double temperatureCoefficientOfViscosity { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
