//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWLOTPH.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Stamp { get; set; }
        public string Description { get; set; }
    
        public virtual MaterialEmpiricalCoefficients MaterialEmpiricalCoefficients { get; set; }
        public virtual MaterialProperties MaterialProperties { get; set; }
    }
}
