//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWLOTPH.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialProperties
    {
        public double Density { get; set; }
        public double MeltingPoint { get; set; }
        public double AverageHeatCapacity { get; set; }
        public int ID { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
