//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWLOTPH.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserMTypeDBContext : DbContext
    {
        public UserMTypeDBContext()
            : base("name=UserMTypeDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditiveData> AdditiveData { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialEmpiricalCoefficients> MaterialEmpiricalCoefficients { get; set; }
        public virtual DbSet<MaterialProperties> MaterialProperties { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
